name: Documentation Links
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "swarms"
